/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasi;

import Controller.BarangController;
import Model.ModelBarang;
import java.awt.Color;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Gibran
 */
public class Frame_Grid_Barang extends javax.swing.JInternalFrame {

    /**
     * @return the max
     */
    public int getMax() {
        return max;
    }

    /**
     * @param max the max to set
     */
    public void setMax(int max) {
        this.max = max;
    }

    /**
     * @return the start
     */
    public int getStart() {
        return start;
    }

    /**
     * @param start the start to set
     */
    public void setStart(int start) {
        this.start = start;
    }

    /**
     * @return the end
     */
    public int getEnd() {
        return end;
    }

    /**
     * @param end the end to set
     */
    public void setEnd(int end) {
        this.end = end;
    }
    
    private int start = 0;
    private int end = 15;
    private int max = 0;
    
    /**
     * Creates new form Frame_Grid_Barang
     */
    public Frame_Grid_Barang() {
        try {
            initComponents();
            this.showGrid(start, end);
        } catch (IOException ex) {
            Logger.getLogger(Frame_Grid_Barang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public Frame_Grid_Barang(int mulai, int akhir) {
        try {
            initComponents();
            this.showGrid(mulai, akhir);
        } catch (IOException ex) {
            Logger.getLogger(Frame_Grid_Barang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1184, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void showGrid(int start, int end) throws IOException {
        BarangController sub = new BarangController();
        List<ModelBarang> subList;
        
        this.setLayout(new GridLayout(5, 3));
        
        subList = sub.getList();
        this.setMax(this.getMax() == 0 ? subList.size() : this.getMax());
        int i = start;

        while (i < end) {
            Grid panel = new Grid();
            panel.getjLabelNama().setText(subList.get(i).getProductName());
            panel.getjLabelHarga().setText("Rp.");
            panel.getjLabelKategori().setText(subList.get(i).getSubcategory().getKategori().getKategori());
            ImageIcon icon = new ImageIcon(".\\splash.png");
            panel.getjLabelImage().setIcon(new ImageIcon(icon.getImage().getScaledInstance(130, 100, Image.SCALE_SMOOTH)));

//            JPanel panel = new JPanel();
//            JLabel label = new JLabel(subList.get(i).getProductName());
//            JLabel kat = new JLabel(subList.get(i).getSubcategory().getKategori().getKategori());
//            JLabel harga = new JLabel("Price : Rp");
//            JButton add = new JButton("Add to Cart");
//
//            panel.add(label);
//            panel.add(kat);
//            panel.add(harga);
//            panel.add(add);
//
//            panel.setLayout(null);
//            panel.setSize(400, 136);
//
//            Font font = label.getFont();
//            Font boldFont = new Font(font.getFontName(), Font.BOLD, 15);
//
//            label.setLocation(150, 10);
//            label.setSize(220, 30);
//
//            label.setFont(boldFont);
//
//            //----------------------
//            font = kat.getFont();
//            Font fontKat = new Font(font.getFontName(), Font.HANGING_BASELINE, 13);
//
//            kat.setLocation(150, 40);
//            kat.setSize(220, 10);
//
//            kat.setFont(fontKat);
//
//            //----------------------
//            font = harga.getFont();
//            Font priceFont = new Font(font.getFontName(), Font.LAYOUT_LEFT_TO_RIGHT, 13);
//
//            harga.setLocation(150, 60);
//            harga.setSize(220, 30);
//
//            harga.setFont(priceFont);
//
//            add.setLocation(150, 90);
//            add.setSize(220, 35);
//            add.addActionListener(new MyActionListener(
//                    subList.get(i).getProductID()));
//            //----------------------
//            
//            panel.setBorder(BorderFactory.createLineBorder(Color.BLACK));
            this.add(panel);
            i++;
        }
//        JPanel foot = new JPanel();
//        
//        foot.setLayout(null);
//        foot.setSize(1200, 136);
//        foot.setBorder(BorderFactory.createLineBorder(Color.BLACK));
//        foot.add(new JLabel("PanasLAH"));
//        
//        frame.add(foot);
    }

    private class MyActionListener implements ActionListener {

        String text;

        public MyActionListener(String text) {
            this.text = text;
        }

        public void actionPerformed(ActionEvent e) {
            System.out.println(text);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
