/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasi;

import Controller.BarangController;
import Controller.KeranjangController;
import Model.ModelBarang;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Gibran
 */
public class Frame_Grid_Barang extends javax.swing.JInternalFrame {
    KeranjangController cart = new KeranjangController();
    /**
     * @return the max
     */
    public int getMax() {
        return max;
    }

    /**
     * @param max the max to set
     */
    public void setMax(int max) {
        this.max = max;
    }

    /**
     * @return the start
     */
    public int getStart() {
        return start;
    }

    /**
     * @param start the start to set
     */
    public void setStart(int start) {
        this.start = start;
    }

    /**
     * @return the end
     */
    public int getEnd() {
        return end;
    }

    /**
     * @param end the end to set
     */
    public void setEnd(int end) {
        this.end = end;
    }
    
    private int start = 0;
    private int end = 15;
    private int max = 0;
    
    /**
     * Creates new form Frame_Grid_Barang
     */
    public Frame_Grid_Barang() {
        try {
            initComponents();
            this.showGrid(start, end);
        } catch (IOException ex) {
            Logger.getLogger(Frame_Grid_Barang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public Frame_Grid_Barang(int mulai, int akhir) {
        try {
            initComponents();
            this.showGrid(mulai, akhir);
        } catch (IOException ex) {
            Logger.getLogger(Frame_Grid_Barang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1184, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void showGrid(int start, int end) throws IOException {
        BarangController sub = new BarangController();
        List<ModelBarang> subList;
        
        this.setLayout(new GridLayout(5, 3));
        
        subList = sub.getList();
        this.setMax(this.getMax() == 0 ? subList.size() : this.getMax());
        int i = start;

        while (i < end) {
            Grid panel = new Grid(); 
            panel.getjLabelNama().setText(subList.get(i).getProductName()); 
            panel.getjLabelHarga().setText("Rp.");
            panel.getjLabelKategori().setText(subList.get(i).getSubcategory().getKategori().getKategori()); 
            ImageIcon icon = new ImageIcon(".\\src\\image\\product.png");
            panel.getjLabelImage().setIcon(new ImageIcon(icon.getImage()));
            panel.getjButtonAdd().addActionListener(new MyActionListener(
                    subList.get(i).getProductID()));

            this.add(panel);
            i++;
        }

    }

    private class MyActionListener implements ActionListener {
        String text;

        public MyActionListener(String text) {
            this.text = text;
        }

        public void actionPerformed(ActionEvent e) {
            String jml = JOptionPane.showInputDialog("Masukan Jumlah Barang");
            cart.tambahBarang(text, Integer.parseInt(jml));
            System.out.println("Total : " + cart.getTotal());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
