/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasi;

import Controller.BarangController;
import Controller.KeranjangController;
import Model.ModelBarang;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.text.DecimalFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author Gibran
 */
public class Frame_Grid_Barang extends javax.swing.JInternalFrame {

    KeranjangController cart = new KeranjangController();

    /**
     * @return the max
     */
    public int getMax() {
        return max;
    }

    /**
     * @param max the max to set
     */
    public void setMax(int max) {
        this.max = max;
    }

    /**
     * @return the start
     */
    public int getStart() {
        return start;
    }

    /**
     * @param start the start to set
     */
    public void setStart(int start) {
        this.start = start;
    }

    /**
     * @return the end
     */
    public int getEnd() {
        return end;
    }

    /**
     * @param end the end to set
     */
    public void setEnd(int end) {
        this.end = end;
    }
    
    private int start = 0;
    private int end = 15;
    private int max = 0;
    int jml;

    /**
     * Creates new form Frame_Grid_Barang
     */
    public Frame_Grid_Barang() {
        try {
            initComponents();
            this.showGrid(start, end);
        } catch (IOException ex) {
            Logger.getLogger(Frame_Grid_Barang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public Frame_Grid_Barang(int mulai, int akhir) {
        try {
            initComponents();
            this.showGrid(mulai, akhir);
        } catch (IOException ex) {
            Logger.getLogger(Frame_Grid_Barang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnPrev = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1200, 717));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(1200, 600));
        jPanel2.setMinimumSize(new java.awt.Dimension(1200, 600));
        jPanel2.setPreferredSize(new java.awt.Dimension(1200, 600));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1201, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(218, 238, 224));

        btnPrev.setText("Previous");
        btnPrev.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPrevMouseClicked(evt);
            }
        });
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });

        btnNext.setText("Next");
        btnNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNextMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(440, 440, 440)
                .addComponent(btnPrev)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrev)
                    .addComponent(btnNext))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1201, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrevMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrevMouseClicked
        if (this.start - 15 >= 0) {

            this.end = this.start;
            this.start = this.start - 15 < 0 ? 0 : this.start - 15;

            Frame_Grid_Barang grid = new Frame_Grid_Barang(start, end);
            jPanel2.removeAll();
            jPanel2.add(grid);
            grid.setVisible(true);
            btnNext.setEnabled(true);
            btnPrev.setEnabled(this.start > 0);
        } else {
            btnPrev.setEnabled(false);
        }
    }//GEN-LAST:event_btnPrevMouseClicked

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrevActionPerformed

    private void btnNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNextMouseClicked
        if (this.end + 15 <= this.max) {

            this.start = this.end;
            this.end = this.end + 15 > this.max ? this.max : this.end + 15;

            Frame_Grid_Barang grid = new Frame_Grid_Barang(start, end);
            jPanel2.removeAll();
            jPanel2.add(grid);
            grid.setVisible(true);
            btnNext.setEnabled(this.end < this.max);
            btnPrev.setEnabled(true);
        } else {
            btnNext.setEnabled(false);
        }
    }//GEN-LAST:event_btnNextMouseClicked

    public void showGrid(int start, int end) throws IOException {
        BarangController sub = new BarangController();
        List<ModelBarang> subList;
        
        jPanel2.setLayout(new GridLayout(5, 3));
        
        subList = sub.getList();
        this.setMax(this.getMax() == 0 ? subList.size() : this.getMax());
        int i = start;
        DecimalFormat decimalFormat = new DecimalFormat("#.00");
        
        while (i < end) {
            Grid panel = new Grid(); 
            panel.setSize(400, 100);
            panel.getjLabelNama().setText(subList.get(i).getProductName());
//            panel.getjLabelHarga().setText("Rp.");
            panel.getjLabelKategori().setText(subList.get(i).getSubcategory().getKategori().getKategori());
            panel.getjLabelHarga().setText("$" + decimalFormat.format(subList.get(i).getPrice()));
            ImageIcon icon = new ImageIcon(subList.get(i).getImageSource());
//            ImageIcon icon = new ImageIcon(".\\src\\image\\product.png");
            panel.getjLabelImage().setIcon(new ImageIcon(icon.getImage()));
            panel.getjButtonAdd().addActionListener(new MyActionListener(subList.get(i).getProductID(),panel));
            panel.getJSpinnerJml().addChangeListener(new ChangeListener() {
                @Override
                public void stateChanged(ChangeEvent e) {
                    JSpinner s = (JSpinner) e.getSource();
                    int val = (int) s.getValue();
                    if (val < 1) {
                        s.setValue(1);
                    }
                    jml = val;
                }
            });
            
            jPanel2.add(panel);
            i++;
        }
        
    }
    
    private class MyActionListener implements ActionListener {
        String text;
        Grid g;
        
        public MyActionListener(String text, Grid panel) {
            this.text = text;
            g = panel;
        }
        
        public void actionPerformed(ActionEvent e) {
            cart.tambahBarang(text, jml);
            System.out.println("Total : " + cart.getTotal());
            g.getJSpinnerJml().setValue(1);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
