/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasi;

import javax.swing.JButton;

/**
 *
 * @author Annazar
 */
public class Grid extends javax.swing.JPanel {

    /**
     * Creates new form Grid
     */
    public Grid() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNama = new javax.swing.JLabel();
        jLabelHarga = new javax.swing.JLabel();
        jLabelKategori = new javax.swing.JLabel();
        jButtonAdd = new javax.swing.JButton();
        jLabelImage = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setMaximumSize(new java.awt.Dimension(400, 136));
        setMinimumSize(new java.awt.Dimension(400, 136));
        setPreferredSize(new java.awt.Dimension(400, 136));

        jLabelNama.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabelNama.setText("NAMA BARANG");
        jLabelNama.setMaximumSize(new java.awt.Dimension(220, 30));
        jLabelNama.setMinimumSize(new java.awt.Dimension(220, 30));
        jLabelNama.setPreferredSize(new java.awt.Dimension(220, 30));

        jLabelHarga.setText("HARGA BARANG");
        jLabelHarga.setMaximumSize(new java.awt.Dimension(220, 30));
        jLabelHarga.setMinimumSize(new java.awt.Dimension(220, 30));
        jLabelHarga.setPreferredSize(new java.awt.Dimension(220, 30));

        jLabelKategori.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        jLabelKategori.setText("KATEGORI BARANG");
        jLabelKategori.setMaximumSize(new java.awt.Dimension(220, 10));
        jLabelKategori.setMinimumSize(new java.awt.Dimension(220, 10));
        jLabelKategori.setPreferredSize(new java.awt.Dimension(220, 10));

        jButtonAdd.setText("ADD TO CART");
        jButtonAdd.setMaximumSize(new java.awt.Dimension(220, 35));
        jButtonAdd.setMinimumSize(new java.awt.Dimension(220, 35));
        jButtonAdd.setPreferredSize(new java.awt.Dimension(220, 35));

        jLabelImage.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelImage, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JLabel jLabelHarga;
    private javax.swing.JLabel jLabelImage;
    private javax.swing.JLabel jLabelKategori;
    private javax.swing.JLabel jLabelNama;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the jButtonAdd
     */
    public javax.swing.JButton getjButtonAdd() {
        return jButtonAdd;
    }

    /**
     * @return the jLabelBarang
     */
    public javax.swing.JLabel getjLabelHarga() {
        return jLabelHarga;
    }

    /**
     * @return the jLabelImage
     */
    public javax.swing.JLabel getjLabelImage() {
        return jLabelImage;
    }

    /**
     * @return the jLabelKategori
     */
    public javax.swing.JLabel getjLabelKategori() {
        return jLabelKategori;
    }

    /**
     * @return the jLabelNama
     */
    public javax.swing.JLabel getjLabelNama() {
        return jLabelNama;
    }
}
